### ISSUE TITLE
TLS issue in Samsung Devices

### ISSUE THREAD

**Issue by danish-dev-rafique** [dkramorov/flutter_xmpp#1]
Basically i'm facing issue in Samsung Devices all devices working Fine it give exception that :

Something went wrong while connecting ,make sure the credentials are right and try again:
W/System.err(29284): org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS [XMPPTCPConnection[not-authenticated] (0)]
W/System.err(29284): at org.jivesoftware.smack.AbstractXMPPConnection.waitForConditionOrThrowConnectionException(AbstractXMPPConnection.java:731)
W/System.err(29284): at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:857)
W/System.err(29284): at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:526)
W/System.err(29284): at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnection.connect(FlutterXmppConnection.java:527)
W/System.err(29284): at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.initConnection(FlutterXmppConnectionService.java:72)
W/System.err(29284): at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.lambda$start$0$org-xrstudio-xmpp-flutter_xmpp-Connection-FlutterXmppConnectionService(FlutterXmppConnectionService.java:93)
W/System.err(29284): at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService$$ExternalSyntheticLambda0.run(Unknown Source:2)
in flutter just on every samsung device this show why

**Comment by danish-dev-rafique** [comment]
basically this issue come from xmpp_flutter pkg which is live on pub.dev

**Comment by danish-dev-rafique** [comment]
Right now i test in this library there is no issue hope fully this will work fine 
i'm contributor of xmpp_flutter library which is on pub.dev
